import os


ENVIRONMENT=os.getenv('ENVIRONMENT')

SLACK_VIP_BALOOT_BOT_OAUTH_TOKEN = os.getenv('SLACK_VIP_BALOOT_BOT_OAUTH_TOKEN')
SLACK_VIP_BALOOT_SIGNING_SECRET = os.getenv('SLACK_VIP_BALOOT_SIGNING_SECRET')

SLACK_AWAD_DELIVERY_BOT_OAUTH_TOKEN = os.getenv('SLACK_AWAD_DELIVERY_BOT_OAUTH_TOKEN')
SLACK_AWAD_DELIVERY_SIGNING_SECRET = os.getenv('SLACK_AWAD_DELIVERY_SIGNING_SECRET')

PLATFORM_OPERATIONS_DB_URL = os.getenv('PLATFORM_OPERATIONS_DB_URL')

PLATFORM_ANALYTICS_DB_HOST = os.getenv('PLATFORM_ANALYTICS_DB_HOST')
PLATFORM_ANALYTICS_DB_PORT = os.getenv('PLATFORM_ANALYTICS_DB_PORT')
PLATFORM_ANALYTICS_DB_USERNAME = os.getenv('PLATFORM_ANALYTICS_DB_USERNAME')
PLATFORM_ANALYTICS_DB_PASSWORD = os.getenv('PLATFORM_ANALYTICS_DB_PASSWORD')
