import os


ENVIRONMENT=os.getenv('ENVIRONMENT')

SLACK_VIP_BALOOT_BOT_OAUTH_TOKEN = os.getenv('SLACK_VIP_BALOOT_BOT_OAUTH_TOKEN')
SLACK_VIP_BALOOT_SIGNING_SECRET = os.getenv('SLACK_VIP_BALOOT_SIGNING_SECRET')

SLACK_AWAD_DELIVERY_BOT_OAUTH_TOKEN = os.getenv('SLACK_AWAD_DELIVERY_BOT_OAUTH_TOKEN')
SLACK_AWAD_DELIVERY_SIGNING_SECRET = os.getenv('SLACK_AWAD_DELIVERY_SIGNING_SECRET')
