-- Create "slack_assistant_context_store" table
CREATE TABLE "public"."slack_assistant_context_store" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "channel_id" character varying NULL,
  "thread_ts" character varying NULL,
  "user_id" character varying NULL,
  "team_id" character varying NULL,
  "context" jsonb NULL,
  "payload" jsonb NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_slack_assistant_context_store__team_id_user_id_channel_id_th" UNIQUE ("channel_id", "thread_ts")
);
-- Create "slack_teams_info" table
CREATE TABLE "public"."slack_teams_info" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "team_id" character varying NULL,
  "name" character varying NULL,
  "url" text NULL,
  "domain" character varying NULL,
  "email_domain" text NULL,
  "avatar_base_url" text NULL,
  "is_verified" boolean NULL,
  "public_url" text NULL,
  "image_default" boolean NULL,
  "image_34" text NULL,
  "image_44" text NULL,
  "image_68" text NULL,
  "image_88" text NULL,
  "image_102" text NULL,
  "image_230" text NULL,
  "image_132" text NULL,
  "lob_sales_home_enabled" boolean NULL,
  "is_sfdc_auto_slack" boolean NULL,
  "payload" jsonb NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_slack_teams_info__team_id" UNIQUE ("team_id")
);
-- Create "slack_conversations_info" table
CREATE TABLE "public"."slack_conversations_info" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "channel_id" character varying NULL,
  "created" timestamptz NULL,
  "creator" character varying NULL,
  "is_org_shared" boolean NULL,
  "is_im" boolean NULL,
  "team_id" character varying NULL,
  "updated" timestamptz NULL,
  "name" character varying NULL,
  "name_normalized" character varying NULL,
  "is_channel" boolean NULL,
  "is_group" boolean NULL,
  "is_mpim" boolean NULL,
  "is_private" boolean NULL,
  "is_archived" boolean NULL,
  "is_general" boolean NULL,
  "is_shared" boolean NULL,
  "is_ext_shared" boolean NULL,
  "unlinked" integer NULL,
  "is_pending_ext_shared" boolean NULL,
  "pending_share" text[] NULL,
  "parent_conversation" character varying NULL,
  "purpose_value" text NULL,
  "purpose_creator" character varying NULL,
  "purpose_last_set" bigint NULL,
  "topic_value" text NULL,
  "topic_creator" character varying NULL,
  "topic_last_set" bigint NULL,
  "shared_team_ids" character varying[] NULL,
  "pending_connected_team_ids" character varying[] NULL,
  "canvas_file_id" character varying NULL,
  "canvas_is_empty" boolean NULL,
  "canvas_quip_thread_id" character varying NULL,
  "canvas_is_migrated" boolean NULL,
  "properties" jsonb NULL,
  "payload" jsonb NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_slack_conversations_info__channel_id_team_id" UNIQUE ("channel_id", "team_id"),
  CONSTRAINT "fk_slack_conversations_info__slack_teams_info" FOREIGN KEY ("team_id") REFERENCES "public"."slack_teams_info" ("team_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "slack_users_info" table
CREATE TABLE "public"."slack_users_info" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "user_id" character varying NULL,
  "name" character varying NULL,
  "is_bot" boolean NULL,
  "updated" timestamptz NULL,
  "is_app_user" boolean NULL,
  "team_id" character varying NULL,
  "deleted" boolean NULL,
  "color" character varying NULL,
  "is_email_confirmed" boolean NULL,
  "real_name" character varying NULL,
  "tz" character varying NULL,
  "tz_label" character varying NULL,
  "tz_offset" integer NULL,
  "is_admin" boolean NULL,
  "is_owner" boolean NULL,
  "is_primary_owner" boolean NULL,
  "is_restricted" boolean NULL,
  "is_ultra_restricted" boolean NULL,
  "who_can_share_contact_card" character varying NULL,
  "display_name" character varying NULL,
  "avatar_hash" character varying NULL,
  "real_name_normalized" character varying NULL,
  "display_name_normalized" character varying NULL,
  "image_24" character varying NULL,
  "image_32" character varying NULL,
  "image_48" character varying NULL,
  "image_72" character varying NULL,
  "image_192" character varying NULL,
  "image_512" character varying NULL,
  "image_1024" character varying NULL,
  "image_original" character varying NULL,
  "is_custom_image" boolean NULL,
  "first_name" character varying NULL,
  "last_name" character varying NULL,
  "email" character varying NULL,
  "title" character varying NULL,
  "phone" character varying NULL,
  "skype" character varying NULL,
  "status_text" character varying NULL,
  "status_text_canonical" character varying NULL,
  "status_emoji" character varying NULL,
  "status_expiration" integer NULL,
  "huddle_state" character varying NULL,
  "huddle_state_expiration_ts" integer NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_slack_users_info__user_id_team_id" UNIQUE ("user_id", "team_id"),
  CONSTRAINT "fk_slack_users_info__slack_teams_info" FOREIGN KEY ("team_id") REFERENCES "public"."slack_teams_info" ("team_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "slack_messages_info" table
CREATE TABLE "public"."slack_messages_info" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "team_id" character varying NULL,
  "user_id" character varying NULL,
  "channel_id" character varying NULL,
  "thread_ts" character varying NULL,
  "message_timestamp" timestamptz NULL,
  "message_type" character varying NULL,
  "ts" character varying NULL,
  "parent_user_id" character varying NULL,
  "TEXT" text NULL,
  "blocks" jsonb NULL,
  "client_msg_id" character varying NULL,
  "channel_type" character varying NULL,
  "event_ts" character varying NULL,
  "files" jsonb NULL,
  "payload" jsonb NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_slack_messages_info__ts_channel_id" UNIQUE ("ts", "channel_id"),
  CONSTRAINT "fk_slack_messages_info__slack_conversations_info" FOREIGN KEY ("team_id", "channel_id") REFERENCES "public"."slack_conversations_info" ("team_id", "channel_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_slack_messages_info__slack_teams_info" FOREIGN KEY ("team_id") REFERENCES "public"."slack_teams_info" ("team_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_slack_messages_info__slack_users_info" FOREIGN KEY ("user_id", "team_id") REFERENCES "public"."slack_users_info" ("user_id", "team_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
