CREATE TABLE IF NOT EXISTS SLACK_ASSISTANT_CONTEXT_STORE (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CHANNEL_ID VARCHAR,
    THREAD_TS VARCHAR,
    USER_ID VARCHAR,
    TEAM_ID VARCHAR,
    CONTEXT JSONB,
    PAYLOAD JSONB
);